apiVersion: ENC[AES256_GCM,data:3EE=,iv:31rpO5251WvsZX1q3P3u+jbSnOKuHACVnbWVlTn0Xtc=,tag:VFctMAR9NvLjgK0/VVBxbw==,type:str]
data:
    telegram-chat-id: ENC[AES256_GCM,data:1aA4r70Db1MIpiNNs6OI2g==,iv:C4qYmcfLkJEDdGweKFJHXF7Ffsn0i5qz4lRrfwe5KdM=,tag:mRx3rrq2i3vZdQoVMzx3Tw==,type:str]
    telegram-token: ENC[AES256_GCM,data:rvX69r5QP1eMxqoWmZhLbjj+SCw8SP/1XfdrBUAFi3JAy5MZJ7ljQo4oZaJcjkuR3YOsoS6ZVn3IgAd//nDpqw==,iv:p3S5wroAivcdXkH/6U4WiNzIODcrcvZHaDCiSqbeesc=,tag:wY+/Dxud3Sm2j/mJu3JU3g==,type:str]
kind: ENC[AES256_GCM,data:KwNseCNd,iv:3JP2/VrwQHvFjx9GberGdkEc1EHepvPfucx6TmWzD1o=,tag:ha5C1wBjgNqs0K+Tf4Gl2A==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:KmvmYV+Drk1EhqGW8bPZBwVfiGVfUlkhbMgK,iv:yEaF5ROfeWFy6HWYhFea7Y7uqmf93dqL8hnjZ/KjF8M=,tag:6G5LKaRRcrG6U1GacffxxA==,type:str]
    namespace: ENC[AES256_GCM,data:ndyYaRRM,iv:G0iib0zpEGGlJi2m70tvQyf0qLfoEKv7nAwg1DHUUUg=,tag:Lb6NP22OVxl3vXYPNhMzQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNjNpVWZrOCs4YXA2cHZS
            cUY2L1NQNjRFZmkycWVQeThkWXoyMUZSQVFnCjltSm9SNUJhbk5laUxEaWtXWG1K
            VzlmQlh5NUF6ZTR2alNycFE0YkNHVkkKLS0tIGxseWp1djljOEV0RTBQaXdqdk5i
            dTZLYmNLZCtXcUx2QVJkd2FaSWNqaDQKq4fTpZTfYILbdsl3VLB71fAu0RQir4DO
            hR4f/IBwB+2xxZ0q+YcKv6/73s6eZit0jEWQCWggz78LkB8F1/ZTsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kttje7qaqggnssmu4a40ptm649wthp0twmd4c9jsjstkpnuptqdqp3fkc0
    lastmodified: "2026-05-17T00:46:13Z"
    mac: ENC[AES256_GCM,data:Gdu+uN5AvlWD7NDaMniwSw3T1Vi4io/XT+ithTXoK47DRsewznhJgeO3C7dbWmWljbADuYgBfgatMoMWmW/mYVUlnRbCJVfxCuFMT5eL6d4el/n5W5CGTW0Fmytf6NWJumCtmPQVgB49bOAxuL/Q5YJ4+9WHkopyoTvs+OnJK04=,iv:aQq9lqLlpymAmVvNe8KT2kXsNHYqTagnUH+qxy4NfZw=,tag:4crjz1y0m+sZYYOooL89VQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
