apiVersion: v1
data:
    telegram-token: ENC[AES256_GCM,data:M2UH4g6eIhRtK85nkQ5GP4ZkMMGZGHXweWzBpQ4IX6pJyk8u60dW0GxQWWvDb3UuRefxxKQs1vmz4412GZVvyg==,iv:FoRcbrGTI02kDho9uojymffkwjuiTXrta4+nh+HG0t0=,tag:qTFVLW5U8aA3h6fvRdvW5w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: argocd-notifications-secret
    namespace: argocd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRzM4eDFUWUxWQ2gyYzkr
            dDg4aEZVSyt3YngyNVh1TWxpVFB6ZS9DTlFnCmtEK1U1RWpQbEcwQnB6WGU1YmRP
            QlBha1JHOXRvRnpJL0NBTXplL3daaHcKLS0tIFMwRlBNemtyTVVrYWxLYjk1V0oy
            VzROam5hUG1XYVlQMzdNTjlJTmFXQ2MK9n8b7fmU0/CGJ+6tSUuhCXnsgKCS4Rjh
            WXce2rxgAcfeCqYesT3nGdrS55fHUSQp1VyXouoLHOuZydLCOEVOFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kttje7qaqggnssmu4a40ptm649wthp0twmd4c9jsjstkpnuptqdqp3fkc0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T20:57:18Z"
    mac: ENC[AES256_GCM,data:IqeczPTGk5P+mJgZwi3bhN+0DK2K1BCzuUNOp0EPdW0jkYUuY49RnWdZbwz4TYYgDS7S9Z0TZETf+U8qtOerwYBKLtdvPNnno1jNLjLcGWeJiu+dv1lpKq02WMassVwLBfbK0J2yUPGj1vebDdPDPr3/q5fp1mT9eXH3FKhCkpU=,iv:mTBHY5Y7d/DHzk4bvXaW08pPgQpL9MItR/04KjpVu8Q=,tag:lWxCW3oopMhlkQWjcWQH1w==,type:str]
    version: 3.13.0
